### ISSUE TITLE
Electron config

### ISSUE THREAD

**Issue by coryarmbrecht** [egoist/poi.js.org#9]
If I [add the Electron config](https://github.com/egoist/poi.js.org) to a my poi.config.js, I receive this error.

```
TypeError: Expected a value of type `undefined` for `webpack` but received `undefined`.
    at Function.Struct.validate.value [as validate] (/Users/poiuser/Projects/poi-electron-test/node_modules/superstruct/lib/index.js:1196:17)
    at module.exports (/Users/poiuser/Projects/poi-electron-test/node_modules/poi/lib/utils/validateConfig.js:156:34)
    at PoiCore.mergeConfig (/Users/poiuser/Projects/poi-electron-test/node_modules/poi/lib/index.js:280:19)
    at new PoiCore (/Users/poiuser/Projects/poi-electron-test/node_modules/poi/lib/index.js:121:10)
    at main (/Users/poiuser/Projects/poi-electron-test/node_modules/poi/bin/cli.js:13:17)
    at Object.<anonymous> (/Users/poiuser/Projects/poi-electron-test/node_modules/poi/bin/cli.js:28:1)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! poi-electron-test@0.0.0 start: `poi --serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the poi-electron-test@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/poiuser/.npm/_logs/2019-04-17T03_38_42_077Z-debug.log
```

If I run poi with an empty config, it will then boot up Electron and be pointed to localhost:4000, but it's not able to run. (es6+).  

Thank you!

**Comment by egoist** [comment]
I don't know what you mean, please open issues in the Poi repo instead and provide mininal reproduction.

**Comment by coryarmbrecht** [comment]
Sorry, I was just realizing that I put this in the wrong repo again. >_<
